export const BUY_CAKE = "BUY_CAKE";
export const BUY_ICECREAM = "BUY_ICECREAM";
export const INCREMENT_COUNTER = "INCREMENT_COUNTER";
export const DECREMENT_COUNTER = "DECREMENT_COUNTER";

export const FETCH_POSTS_REQUEST = "FETCH_POSTS_REQUEST";
export const FETCH_POSTS_SUCESS = "FETCH_POSTS_SUCESS";
export const FETCH_POSTS_FAILURE = "FETCH_POSTS_FAILURE";
